### PR TITLE
Disconnect client only if Slack disconnect is intentional

### PR DESCRIPTION
**Pull request by insomniacslk**
If the disconnection from Slack is intentiona, just keep closing the IRC
client connection as previously. However, if the disconnection is not
intentional, it's not necessary to disconnect the IRC client, as the
Slack reconnection will be handled by Slack's RTM.ManageConnection.
This should reduce the amount of disconnect/reconnect on the IRC client
side.

Signed-off-by: Andrea Barberio <insomniac@slackware.it>

### CODE REVIEW

**Comment by janza** [comment]
Do we queue the messages that are received on IRC while we're disconnected from slack, or are they lost?

**Comment by insomniacslk** [comment]
These are lost unfortunately, in any case

**Comment by insomniacslk** [comment]
There should be a call to get the history, but then we would have to queue them in irc-slack

**Comment by insomniacslk** [comment]
In practice, with this change the likelihood of missing an event from Slack is lower than before

**Comment by insomniacslk** [comment]
Mh, this may have broken irc-slack, it seems the connection is not always reestablished

**Comment by janza** [comment]
Can confirm, I'm getting connection issues with the latest master

**Comment by insomniacslk** [comment]
I will revert it now

**Comment by insomniacslk** [comment]
@janza can you please look at https://github.com/insomniacslk/irc-slack/pull/121 ?

**Pull request merged**
