### PR TITLE
Split long replies if requested with -chunk

### LINKED ISSUE #38: ZNC having issues with too long of a message
Today I was trying to connect to a slack where a channel that I was forced to belong to had 450+ users in it. The problem is that my ZNC bouncer was disconnecting because a command was being sent to the client that exceeded its limits. Here is an example of the messages that are being sent:

Sending numeric reply: :irc-slack-name-here 353 myUsername = #general :(list of users that is 450+ characters)

According to [this](https://github.com/znc/znc/issues/971#issuecomment-108527488) bug report that the server shouldn't send over 512 total bytes per message in total (according to the RFC). I believe that ZNC (further on in that bug) allows up to 1024 total bytes per message.

I believe the solution would be to chunk the data (512 byte chunks) sent to the client so that they don't freak out in any manner. The method in question is [here](https://github.com/insomniacslk/irc-slack/blob/edca6dde10e062649a69b023a174abeba749e9a0/irc_server.go#L89).

Sorry for the multiple bugs today.

### PR DESCRIPTION
**Pull request by insomniacslk**
Fixes #38

### CODE REVIEW

**Comment by insomniacslk** [comment]
@Syloq can you try this patch? More testing is coming

**Comment by Syloq** [comment]
I'm getting the same result as before the patch. I need to really debug the ZNC connection and see what is going on exactly. I see that you send the numeric 353 but ZNC does not like it and replies with a :"**Received a too long line from the IRC server!**" to the IRC client. I can't be exactly sure what is triggering the error. I'll look at it more tonight.

**Comment by insomniacslk** [comment]
Have you run it with `-chunk 512` ?

**Comment by insomniacslk** [comment]
also CC @chex3, you have a lot of experience with large Slack teams :)

**Comment by Syloq** [comment]
> Have you run it with `-chunk 512` ?

Ugh, sorry I misunderstood what you did there. Yes, that appears to work as expected.

**Comment by insomniacslk** [comment]
it seems to fix some issues that I have on another large Slack team that I use for testing - now I don't have random surprises with the nick list anymore. I think it may be good to have this as default - maybe 1024 like most clients can deal with? Or 512 to make everyone happy at the cost of over-chunking?

**Comment by Syloq** [comment]
I'd go with 512 as the default and allow people to change it via the switch on the command line if they see fit. Seems like the best of both worlds.

**Comment by insomniacslk** [comment]
Alright, be it 512. Testing and merging soon

**Comment by Syloq** [comment]
So, I'm not sure if this is related. I have the chunking working properly now, but after running the irc-slack app for over a few hours with little to no activity I am no longer getting messages from slack. I see people sending them privately or in a channel via the slack web interface, but it isn't showing up in the client, nor in the log of the app itself.

I know this isn't overly helpful information. But I'm not sure if its related to this change or not.

**Comment by insomniacslk** [comment]
@Syloq do you see any relevant or weird message in the status bar? Or in the irc-slack logs?

**Pull request merged**
