### PR TITLE
Batch messages sent to slack

### PR DESCRIPTION
**Pull request by janza**
This allows sending multiple consecutive messages as a single multiline message to slack api.
I find this useful for sending code snippets that span multiple lines.

### CODE REVIEW

**Comment by insomniacslk** [comment]
this now conflicts with the master branch after I merged your other PRs, can you please fix it before I review? Thanks!

**Comment by insomniacslk** [comment]
I still see merge conflicts with server.go and irc_context.go

**Comment by janza** [comment]
Now?

**Comment by insomniacslk** [comment]
according to the GitHub UI it's still conflicting, you should see it below in the checks - it says "This branch cannot be rebased due to conflicts". I also tried via cmdline and I see the same conflicts. Let me know if you need help, I can commit on top of your branch

**Comment by janza** [comment]
Strange I see `This branch has no conflicts with the base branch` https://puull.pw/17a3.png. Am I looking at a wrong thing?

**Comment by janza** [comment]
I'm probably because it's a rebase merge, so I need to rebase it on top of master. Will do that in a bit.

**Comment by insomniacslk** [comment]
Just tested and it works nicely :) my client has throttling, so I see the first few lines in a batch, and the remaining ones split one per line, but I'd say it's a great step ahead anyway :) Thanks @janza !

**Pull request merged**
