### PR TITLE
Show reactions to messages in the chat log

### PR DESCRIPTION
**Pull request by janza**
This commits adds a feature to log reactions to messages. The reaction
will be logged as an IRC action:

    <nick> reacted with <reaction> to: <msg text up to 100 characters>

### CODE REVIEW

**Comment by insomniacslk** [comment]
hey @janza , thanks a lot for this PR! I will review it later today

**Comment by insomniacslk** [comment]
I made a quick test and got this:
```
* | insomniac reacted with grin to: <unknown>
```
seems like this is almost ready :)

**Comment by insomniacslk** [comment]
The build is failing, it seems that nlopes/slack has changed interface (and we don't use go modules):
```
./irc_server.go:418:35: info.Users undefined (type *slack.Info has no field or method Users)
./irc_server.go:419:35: info.Channels undefined (type *slack.Info has no field or method Channels)
./irc_server.go:420:35: info.Groups undefined (type *slack.Info has no field or method Groups)
./irc_server.go:421:35: info.Bots undefined (type *slack.Info has no field or method Bots)
./irc_server.go:422:35: info.IMs undefined (type *slack.Info has no field or method IMs)
```

**Comment by janza** [comment]
Fixed the `<unknown>` bit, sorry for that. It now loads text of the message if the message is not found in the cache (last 100 messages). #74 should take care of failing build.

**Comment by insomniacslk** [comment]
Thanks @janza ! I just merged #74, can you please rebase this?

**Comment by insomniacslk** [comment]
hm... still red

```
./event_handler.go:48: Printf format %s has arg channel of wrong type *github.com/nlopes/slack.Channel
./event_handler.go:52: Printf format %s has arg openingText of wrong type github.com/nlopes/slack.Message
```

**Comment by insomniacslk** [comment]
works perfectly, thanks @janza !

**Pull request merged**
